media:
  input: assets/img
  output: /assets/img
  # Lưu ý: Thêm dấu / ở cuối link
  public_url: https://cdn.jsdelivr.net/gh/Blueky-Hub/blueky@main/assets/img/

collections:
  - name: gallery
    label: "Kho Ảnh CDN"
    folder: content/gallery
    extension: json
    create: true
    fields:
      - { label: "Tên gợi nhớ", name: title, widget: string }
      - { 
          label: "Link CDN (Copy tại đây)", 
          name: image_url, 
          widget: image 
        }