media:
  input: assets/img
  output: /assets/img
  public_url: https://cdn.jsdelivr.net/gh/Blueky-Hub/blueky@main/assets/img/

content:
  - name: gallery
    label: "Media Gallery (Lấy Link)"
    type: collection
    path: content/gallery
    format: json
    fields:
      - name: title
        label: "Tên ảnh"
        type: string
      - name: link_finder
        label: "Mở mục này để Copy Link"
        type: object
        fields:
          - name: url
            label: "Link CDN của bạn"
            type: image